<?php

namespace Tests\AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\HttpFoundation\Response;
use Tests\AppBundle\Controller\BaseTestCase;

require_once 'BaseTestCase.php';

class ProductControllerTest extends BaseTestCase
{
//    public function setUp()
//    {
//        parent::setUp(); // TODO: Change the autogenerated stub
//        // load fixtures
//        $this->setUpMysql();
//        $this->setUpMysqlFixtures();
//    }

    public static function setUpBeforeClass()
    {
        self::tearDownMysql();
        self::setUpMysql();
        self::setUpMysqlFixtures();
    }

    public static function tearDownAfterClass()
    {
//        self::tearDownMysql();
    }


        static::assertTrue($client->getResponse()->isRedirect('http://foxweb24.ru/php_coaching/'));
        static::assertEquals(Response::HTTP_FOUND, $client->getResponse()->getStatusCode());

}